### PR TITLE
1.16 support

### PR DESCRIPTION
**Pull request by forkiesassds**
This should add working 1.16 support for this plugin, untested due to having no idea on how to build this, you better add a build script that builds the source.

### CODE REVIEW

**Comment by stylextv** [comment]
Thank you! For some weird reason, github didn't notify about this pull request so I am seeing it now for the first time.
I am currently on vacation but once I am back I'll test it.

**Comment by forkiesassds** [comment]
1.16 also adds new colors to use on maps, so this means we can increase the amount of colors we can display.

**Comment by stylextv** [comment]
Oh I didn't even so those new colors (7, right?).
Thats awesome!
But it also means I have to add another color table into "assets/color_tables" which is going to make the jar even bigger...

**Comment by forkiesassds** [comment]
Can't we just combine all of the color tables to a single color table? And address the amount of colors that a specific version can use

**Comment by stylextv** [comment]
I dont think so. You see, when converting real Image colors to map colors, searching for the correct map color for each pixel is way too slow. Thats why I use these look-up tables.
If I want to know what map color to use for any pixel I just look it up, which is A LOT faster.
Unfortunately this comes with the cost of having to include these tables somewhere in your plugin.
My entire code is currently around 200kb and the tables are 300kb...

Combining them would also not work because these files are basically just a compressed way of listing ONE map color for each image color.
I could combine the tables into 1 single table but that would than have the exact same sizes as the uncombined ones together.

I also thought about storing like the 1.12 table in its entirety and for the 1.16 table only store the differences between them, because they are very similar.
But I don't think that would work, because of the algorithm that compresses the tables.

**Comment by forkiesassds** [comment]
What if we make a base color table which contains 1.8.8 colors and then use smaller color tables for colors in newer versions

**Comment by stylextv** [comment]
"I also thought about storing like the 1.12 table in its entirety and for the 1.16 table only store the differences between them, because they are very similar.
But I don't think that would work, because of the algorithm that compresses the tables."

Using 1 color table as a base would be very hard if not impossible, without giving up on the compression.
Btw one single table would be 16MB uncompressed...

**Comment by stylextv** [comment]
Integrated the pull request into my local project. Thanks for the contribution 👍

**Pull request closed without merging**
